

-- This file contains all the global variables for all Pattern Editor functions. 

-- Navigation constants
UP = 1
DOWN = 2
JUMP_STEP = 1
JUMP_MAX = 64

-- Edit modes
LINE = 1
COLUMN = 2
NOTE_PROPERTIES = 3
ALL_BUT_NOTE = 4
NOTE_ONLY = 5
EFFECTS_ONLY = 6

-- Default edit mode
EDIT_MODE = LINE

-- Note column properties
NOTE = 1
VOL = 2
PAN = 3
DELAY = 4
NOTE_FX = 5
DEFAULT_NOTE_PROPERTY = VOL

-- Subdivisions
EIGHTH = 1
SIXTEENTH = 2

-- FX parameters
X = "x"
Y = "y"

-- FX columns
FX1 = 1
FX2 = 2
FX3 = 3
FX4 = 4
FX5 = 5
FX6 = 6
FX7 = 7
FX8 = 8
DEFAULT_FX_COLUMN = 1

-- FX Edit Modes
FX_LOCAL = "LOCAL"
FX_TRACK = "TRACK"
FX_MASTER = "MASTER"
FX_EDIT_MODE = FX_LOCAL

-- General FX Types
ARPEGGIO = "ARPEGGIO"
SLIDE_UP = "SLIDE UP"
SLIDE_DOWN = "SLIDE DOWN"
GLIDE_TO_NOTE = "GLIDE TO NOTE"
VIBRATO = "VIBRATO"
FADE_VOLUME_IN = "FADE VOLUME IN"
FADE_VOLUME_OUT = "FADE VOLUME OUT"
TREMOLO = "TREMOLO"
CUT_VOLUME = "CUT VOLUME"
TRIGGER_SAMPLE = "TRIGGER SAMPLE"
PLAY_SAMPLE_BACKWARDS = "PLAY SAMPLE BACKWARDS"
SET_ENVELOPE_POSITION = "SET ENVELOPE POSITION"
AUTO_PAN = "AUTO PAN"

-- Note properties FX
DELAY_25 = "DELAY 25%"
DELAY_50 = "DELAY 50%"
DELAY_75 = "DELAY 75%"

-- Renoise specific FX types
TRIGGER_PHRASE = "TRIGGER PHRASE"
PLAY_PHRASE_BACKWARDS = "PLAY PHRASE BACKWARDS"

-- Instrument Commands
MUTE_CHANNEL = "MUTE CHANNEL"
TRIGGER_PHRASE_NUMBER = "TRIGGER PHRASE NUMBER"
DELAY_LINE_PLAYBACK = "DELAY LINE PLAYBACK"
MAYBE_TRIGGER = "MAYBE TRIGGER"
RETRIGGER_INSTRUMENT = "RETRIGGER INSTRUMENT"

-- Device commands
MUTE_PREMIXER = "MUTE PREMIXER"
PAN_PREMIXER = "PAN PREMIXER"
WIDTH_PREMIXER = "WIDTH PREMIXER"
STOP_ALL_NOTES = "STOP ALL NOTES"

-- Global commands
SET_BPM = "SET BPM"
SET_LINES_PER_BEAT = "SET LINES PER BEAT"
SET_TPL = "SET TPL"
TOGGLE_SONG_GROOVE = "TOGGLE SONG GROOVE"
BREAK_PATTERN = "BREAK PATTERN"
DELAY_PATTERN = "DELAY PATTERN"

